### ISSUE TITLE
Program doesn't work at all

### ISSUE THREAD

**Issue by y0ti** [firedigger/osuReplayAnalyzer#10]
**osuDodgyMomentsFinder.exe:**
If there's no settings.txt file, program creates it with message "A settings file has been created for you to link to your songs folder."
If settings.txt is present (no matter if settings are correct or not), program throws an exception:
![ss 2016-10-05 at 12 49 07](https://cloud.githubusercontent.com/assets/2990618/19102409/3d16a85a-8afa-11e6-85a4-a2d2bf7138af.png)

**GUI.exe**
If there's no settings.txt file, GUI.exe starts up, but clicking on "Open osu!.db" and choosing osu!.db file and songs folder makes program fail.
![ss 2016-10-05 at 12 55 30](https://cloud.githubusercontent.com/assets/2990618/19102569/6ef6712e-8afb-11e6-86c5-528860d21cd8.png)
If settings.txt is present (no matter if settings are correct or not), then no GUI is shown, GUI.exe process just stays in process list for ~3 seconds, then disappears.

**Comment by firedigger** [comment]
New release is on the way and hopefully will fix the problems
