### ISSUE TITLE
averageKeyPressTime not calculated correctly.

### ISSUE THREAD

**Issue by SaltBlocks** [firedigger/osuReplayAnalyzer#16]
calcPressIntervals() doesn't sort the clicks based on their length.
Since the list isn't sorted, Utils.median(keyPressIntervals) doesn't return the median keypresstime but the holdtime of the click midway through the replay (Or the average of the two middle clicks if the number of clicks is even). 
Because of this, relax / timewarp detection based on the average key press time calculated by the analyzer is currently not valid.

**Comment by firedigger** [comment]
Utils.median uses NthOrderStatistic to get the median, which is more efficient since it doesn't require sorting the full list when we only need 1 position. Look throught the code.

**Comment by SaltBlocks** [comment]
With all due respect, using an NthOrderStatistic does require you to order the list.

Perhaps it'll be more clear if I give an example in which it doesn't function properly without sorting.
I edited a map to contain 9 circles in the same location each with a 500ms delay between them except for the 5th circle. Between the 5th and 6th circle there is a 10000ms delay. When playing the map I held the z key down for as long as I could when the 5th circle appeared. Because the list isn't ordered, this causes the analyzer to display 9883ms as the median key press interval as this is the middlemost click in the replay. Ordering the list fixes the problem and changes the result to 68ms. If ordering wasn't necessary the value shouldn't change at all.

[Replay + map.zip](https://github.com/firedigger/osuReplayAnalyzer/files/1427142/Replay.map.zip)

Screenshot of the result:
![sorted unsorted](https://user-images.githubusercontent.com/29668019/32170745-1f454534-bd76-11e7-878e-5d0c5470e916.png)

**Comment by firedigger** [comment]
I used the wrong method in the code, argh. I got the error now, thanks a lot! Will fix in the upcoming release.
